"""High-quality original SAT Math questions expanding the question bank to 80+ Math questions.

Covers all 4 Digital SAT Math domains and all 29 canonical skills with:
- 100% original content (no scraped College Board or Khan Academy content)
- KaTeX mathematical formatting ($...$ and $$...$$)
- Step-by-step explanations
- Strategic hints and SAT shortcuts
- Desmos calculator hints and flags
- Difficulty balance: ~30% Easy, ~45% Medium, ~25% Hard
"""
from typing import Dict, List
from backend.app.models.enums import Difficulty, MathDomain, Subject

ADDITIONAL_MATH_QUESTIONS: List[Dict] = [
    # =========================================================================
    # DOMAIN 1: ALGEBRA (14 new questions -> 21 total Algebra)
    # =========================================================================
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Linear equations in one variable",
        "subskill": "Multi-step linear equation solving",
        "difficulty": Difficulty.EASY.value,
        "question_text": "If $4(2x - 3) = 28$, what is the value of $x$?",
        "explanation": "Distribute the 4: $8x - 12 = 28$. Add 12 to both sides: $8x = 40$. Divide both sides by 8: $x = 5$. Alternatively, divide by 4 first: $2x - 3 = 7 \\implies 2x = 10 \\implies x = 5$.",
        "hint": "Divide both sides by 4 first to make the mental math faster.",
        "sat_shortcut": "Dividing both sides by 4 immediately yields $2x - 3 = 7$, saving you a distribution step.",
        "estimated_time_seconds": 40,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "3", "is_correct": False},
            {"label": "B", "text": "4", "is_correct": False},
            {"label": "C", "text": "5", "is_correct": True},
            {"label": "D", "text": "7", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Linear equations in one variable",
        "subskill": "Rational linear equations",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "If $\\frac{3x - 5}{4} = \\frac{x + 7}{2}$, what is the value of $x$?",
        "explanation": "Multiply both sides by the common denominator 4: $3x - 5 = 2(x + 7)$. Expand the right-hand side: $3x - 5 = 2x + 14$. Subtract $2x$ from both sides: $x - 5 = 14$. Add 5 to both sides: $x = 19$.",
        "hint": "Cross-multiply or multiply both sides by 4 to eliminate the denominators.",
        "sat_shortcut": "Multiplying both sides by 4 leaves $3x - 5 = 2x + 14$, isolating $x = 19$ in seconds.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "12", "is_correct": False},
            {"label": "B", "text": "15", "is_correct": False},
            {"label": "C", "text": "19", "is_correct": True},
            {"label": "D", "text": "24", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Linear equations in two variables",
        "subskill": "Evaluating two-variable linear equations",
        "difficulty": Difficulty.EASY.value,
        "question_text": "If $5x + 2y = 31$ and $x = 3$, what is the value of $y$?",
        "explanation": "Substitute $x = 3$ into the equation: $5(3) + 2y = 31 \\implies 15 + 2y = 31$. Subtract 15 from both sides: $2y = 16$. Divide by 2: $y = 8$.",
        "hint": "Substitute the given value for $x$ directly into the equation.",
        "sat_shortcut": "Subtract $15$ from $31$ to get $16$, then divide by 2 to get $8$.",
        "estimated_time_seconds": 35,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "6", "is_correct": False},
            {"label": "B", "text": "7", "is_correct": False},
            {"label": "C", "text": "8", "is_correct": True},
            {"label": "D", "text": "11", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Linear equations in two variables",
        "subskill": "Rearranging formulas",
        "difficulty": Difficulty.HARD.value,
        "question_text": "The equation $ax + by = c$ relates variables $x$ and $y$, where $a, b,$ and $c$ are non-zero constants. Which of the following expresses $y$ in terms of $a, b, c,$ and $x$?",
        "explanation": "To solve for $y$: subtract $ax$ from both sides to get $by = c - ax$. Then divide both sides by $b$: $y = \\frac{c - ax}{b}$. This can also be written as $y = -\\frac{a}{b}x + \\frac{c}{b}$.",
        "hint": "Isolate the term containing $y$ first, then divide by its coefficient.",
        "sat_shortcut": "Look at the slope-intercept form $y = -\\frac{a}{b}x + \\frac{c}{b}$.",
        "estimated_time_seconds": 65,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$y = \\frac{c - ax}{b}$", "is_correct": True},
            {"label": "B", "text": "$y = \\frac{c + ax}{b}$", "is_correct": False},
            {"label": "C", "text": "$y = \\frac{ax - c}{b}$", "is_correct": False},
            {"label": "D", "text": "$y = c - \\frac{ax}{b}$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Linear functions",
        "subskill": "Function notation and evaluation",
        "difficulty": Difficulty.EASY.value,
        "question_text": "The linear function $f$ is defined by $f(x) = 3x - 8$. What is the value of $f(7)$?",
        "explanation": "Substitute $x = 7$ into $f(x)$: $f(7) = 3(7) - 8 = 21 - 8 = 13$.",
        "hint": "Replace every occurrence of $x$ with 7.",
        "sat_shortcut": "Mental math: $21 - 8 = 13$.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "11", "is_correct": False},
            {"label": "B", "text": "13", "is_correct": True},
            {"label": "C", "text": "15", "is_correct": False},
            {"label": "D", "text": "21", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Linear functions",
        "subskill": "Determining linear function from two points",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "For the linear function $g$, it is known that $g(0) = 4$ and $g(3) = 13$. What is the value of $g(8)$?",
        "explanation": "Since $g(0) = 4$, the $y$-intercept is $b = 4$. The rate of change is $m = \\frac{g(3) - g(0)}{3 - 0} = \\frac{13 - 4}{3} = \\frac{9}{3} = 3$. The function is $g(x) = 3x + 4$. For $x = 8$, $g(8) = 3(8) + 4 = 24 + 4 = 28$.",
        "hint": "Find the constant rate of change (slope) using the two given points $(0, 4)$ and $(3, 13)$.",
        "sat_shortcut": "Every 1 step in $x$ adds 3 to $g(x)$. From $x=3$ to $x=8$ is $\\Delta x = 5$, so add $5 \\times 3 = 15$ to $13$: $13 + 15 = 28$.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "24", "is_correct": False},
            {"label": "B", "text": "26", "is_correct": False},
            {"label": "C", "text": "28", "is_correct": True},
            {"label": "D", "text": "31", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Systems of linear equations",
        "subskill": "Elimination method",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "Consider the system of equations:\n\n$$3x - 2y = 12$$\n$$x + 2y = 8$$\n\nWhat is the value of $x$?",
        "explanation": "Add the two equations together to eliminate $y$: $(3x + x) + (-2y + 2y) = 12 + 8 \\implies 4x = 20 \\implies x = 5$.",
        "hint": "Notice the $-2y$ and $+2y$ terms. Adding the two equations directly eliminates $y$.",
        "sat_shortcut": "Add directly: $4x = 20 \\implies x = 5$.",
        "estimated_time_seconds": 45,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "3", "is_correct": False},
            {"label": "B", "text": "4", "is_correct": False},
            {"label": "C", "text": "5", "is_correct": True},
            {"label": "D", "text": "6", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Systems of linear equations",
        "subskill": "No solution conditions",
        "difficulty": Difficulty.HARD.value,
        "question_text": "In the system of equations below, $k$ is a constant:\n\n$$6x - 4y = 9$$\n$$kx - 2y = 5$$\n\nIf the system has no solution, what is the value of $k$?",
        "explanation": "For a system of linear equations to have no solution, the lines must be parallel (same slope) with different $y$-intercepts. Multiply the second equation by 2: $2kx - 4y = 10$. Matching coefficients with the first equation: $2k = 6 \\implies k = 3$. Since the constants $9 \\neq 10$, the lines are parallel and distinct, meaning no solution exists.",
        "hint": "Two linear equations have no solution when they have equal slopes but different constants.",
        "sat_shortcut": "Set ratios of coefficients equal: $\\frac{6}{k} = \\frac{-4}{-2} = 2 \\implies k = 3$.",
        "estimated_time_seconds": 60,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "2", "is_correct": False},
            {"label": "B", "text": "3", "is_correct": True},
            {"label": "C", "text": "6", "is_correct": False},
            {"label": "D", "text": "12", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Linear inequalities",
        "subskill": "Single variable inequality solution set",
        "difficulty": Difficulty.EASY.value,
        "question_text": "What is the greatest integer solution to the inequality $5x - 7 \\le 3x + 11$?",
        "explanation": "Subtract $3x$ from both sides: $2x - 7 \\le 11$. Add 7 to both sides: $2x \\le 18$. Divide by 2: $x \\le 9$. The greatest integer satisfying $x \\le 9$ is 9.",
        "hint": "Isolate $x$ on one side of the inequality.",
        "sat_shortcut": "Solve the equality $2x = 18 \\implies x = 9$.",
        "estimated_time_seconds": 40,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "7", "is_correct": False},
            {"label": "B", "text": "8", "is_correct": False},
            {"label": "C", "text": "9", "is_correct": True},
            {"label": "D", "text": "10", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Linear inequalities",
        "subskill": "Budget and constraint inequalities",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "A student has at most \\$120 to spend on notebooks and pens. Each notebook costs \\$12 and each pen costs \\$8. If the student buys 6 notebooks, what is the maximum number of pens they can buy?",
        "explanation": "Let $p$ be the number of pens. The total cost is $12(6) + 8p \\le 120$. Calculate notebook cost: $72 + 8p \\le 120$. Subtract 72: $8p \\le 48$. Divide by 8: $p \\le 6$. The maximum number of pens is 6.",
        "hint": "Set up an inequality with $12 \\times (\\text{notebooks}) + 8 \\times (\\text{pens}) \\le 120$.",
        "sat_shortcut": "$120 - 72 = 48$, and $48 / 8 = 6$.",
        "estimated_time_seconds": 50,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "4", "is_correct": False},
            {"label": "B", "text": "5", "is_correct": False},
            {"label": "C", "text": "6", "is_correct": True},
            {"label": "D", "text": "7", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Slope and intercept",
        "subskill": "Perpendicular line equations",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "Line $k$ in the $xy$-plane is perpendicular to the line $y = -\\frac{2}{3}x + 4$ and passes through the point $(4, 1)$. What is the $y$-intercept of line $k$?",
        "explanation": "The slope of the given line is $-\\frac{2}{3}$. Perpendicular lines have negative reciprocal slopes, so the slope of line $k$ is $m = \\frac{3}{2}$. Using point-slope form with $(4, 1)$: $y - 1 = \\frac{3}{2}(x - 4) \\implies y - 1 = \\frac{3}{2}x - 6 \\implies y = \\frac{3}{2}x - 5$. Therefore, the $y$-intercept is $(0, -5)$, or $-5$.",
        "hint": "The negative reciprocal of $-\\frac{2}{3}$ is $+\\frac{3}{2}$.",
        "sat_shortcut": "Negative reciprocal slope is $1.5$. In Desmos, type `y - 1 = 1.5(x - 4)` and look at the $y$-intercept: $(0, -5)$.",
        "estimated_time_seconds": 60,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "$-7$", "is_correct": False},
            {"label": "B", "text": "$-5$", "is_correct": True},
            {"label": "C", "text": "$-3$", "is_correct": False},
            {"label": "D", "text": "$5$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Slope and intercept",
        "subskill": "Interpreting slope in context",
        "difficulty": Difficulty.HARD.value,
        "question_text": "The equation $C = 45 + 0.22m$ gives the total monthly cost $C$, in dollars, of a cell phone plan when $m$ megabytes of extra data are used. What is the best interpretation of the number $0.22$ in this context?",
        "explanation": "In the linear model $C = 45 + 0.22m$, the rate of change (slope) with respect to $m$ is $0.22$. This represents the cost, in dollars, for each additional megabyte of extra data used.",
        "hint": "Slope is $\\frac{\\Delta C}{\\Delta m}$, representing the change in cost per unit increase in megabytes.",
        "sat_shortcut": "The constant $45$ is the base fee; the coefficient of $m$ is the per-unit rate.",
        "estimated_time_seconds": 50,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "The monthly base cost before any extra data is used", "is_correct": False},
            {"label": "B", "text": "The cost, in dollars, for each additional megabyte of extra data used", "is_correct": True},
            {"label": "C", "text": "The maximum number of megabytes that can be used", "is_correct": False},
            {"label": "D", "text": "The total number of months the phone plan has been active", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Word problems with linear relationships",
        "subskill": "Fixed plus variable cost model",
        "difficulty": Difficulty.EASY.value,
        "question_text": "A car rental company charges a flat fee of \\$40 per day plus \\$0.15 per mile driven. If a customer rents a car for 3 days and drives 200 miles, what is the total rental cost?",
        "explanation": "Flat fee for 3 days: $3 \\times 40 = 120$. Mileage cost for 200 miles: $200 \\times 0.15 = 30$. Total rental cost: $120 + 30 = 150$ dollars.",
        "hint": "Multiply the daily fee by the number of days, and the mileage rate by the number of miles.",
        "sat_shortcut": "Calculate $3(40) + 200(0.15) = 120 + 30 = 150$.",
        "estimated_time_seconds": 45,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "\\$135", "is_correct": False},
            {"label": "B", "text": "\\$140", "is_correct": False},
            {"label": "C", "text": "\\$150", "is_correct": True},
            {"label": "D", "text": "\\$170", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ALGEBRA.value,
        "skill": "Word problems with linear relationships",
        "subskill": "Two-variable mixture word problem",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "A theater sold 150 tickets for a performance. Student tickets cost \\$10 each and adult tickets cost \\$15 each. If the total ticket sales revenue was \\$1,800, how many adult tickets were sold?",
        "explanation": "Let $s$ be student tickets and $a$ be adult tickets. We have $s + a = 150$ and $10s + 15a = 1800$. From the first equation, $s = 150 - a$. Substitute into the revenue equation: $10(150 - a) + 15a = 1800 \\implies 1500 - 10a + 15a = 1800 \\implies 5a = 300 \\implies a = 60$.",
        "hint": "Set up a system: $s + a = 150$ and $10s + 15a = 1800$, then solve for $a$.",
        "sat_shortcut": "If all 150 were student tickets, total revenue would be $1500$. The extra $300$ revenue comes from adults paying $5$ more per ticket: $300 / 5 = 60$ adult tickets.",
        "estimated_time_seconds": 65,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "50", "is_correct": False},
            {"label": "B", "text": "60", "is_correct": True},
            {"label": "C", "text": "75", "is_correct": False},
            {"label": "D", "text": "90", "is_correct": False},
        ],
    },

    # =========================================================================
    # DOMAIN 2: ADVANCED MATH (14 new questions -> 21 total Advanced Math)
    # =========================================================================
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Quadratic equations",
        "subskill": "Factoring quadratic equations",
        "difficulty": Difficulty.EASY.value,
        "question_text": "What is the positive solution to the equation $(x - 5)(x + 3) = 0$?",
        "explanation": "Set each factor equal to zero: $x - 5 = 0 \\implies x = 5$ or $x + 3 = 0 \\implies x = -3$. The positive solution is $x = 5$.",
        "hint": "Set the factor $(x - 5)$ equal to 0.",
        "sat_shortcut": "Immediately read root $x = 5$.",
        "estimated_time_seconds": 25,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "2", "is_correct": False},
            {"label": "B", "text": "3", "is_correct": False},
            {"label": "C", "text": "5", "is_correct": True},
            {"label": "D", "text": "8", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Quadratic equations",
        "subskill": "Sum and product of quadratic roots",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "What is the sum of the solutions to the equation $2x^2 - 8x - 10 = 0$?",
        "explanation": "By Vieta's formulas, for a quadratic equation $ax^2 + bx + c = 0$, the sum of the solutions is $-\\frac{b}{a}$. Here $a = 2$ and $b = -8$, so the sum is $-\\frac{-8}{2} = \\frac{8}{2} = 4$. (Factoring verifies: $2(x^2 - 4x - 5) = 2(x - 5)(x + 1) = 0$, roots are $5$ and $-1$, sum is $5 + (-1) = 4$).",
        "hint": "Use the sum of roots formula: $-\\frac{b}{a}$.",
        "sat_shortcut": "Vieta's formula shortcut: sum is always $-b/a = -(-8)/2 = 4$ in 3 seconds.",
        "estimated_time_seconds": 45,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$-4$", "is_correct": False},
            {"label": "B", "text": "2", "is_correct": False},
            {"label": "C", "text": "4", "is_correct": True},
            {"label": "D", "text": "8", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Quadratic equations",
        "subskill": "Discriminant and single real root",
        "difficulty": Difficulty.HARD.value,
        "question_text": "In the equation $x^2 + kx + 16 = 0$, $k$ is a positive constant. If the equation has exactly one real solution, what is the value of $k$?",
        "explanation": "A quadratic equation $ax^2 + bx + c = 0$ has exactly one real solution when its discriminant is zero: $\\Delta = b^2 - 4ac = 0$. Here, $a = 1$, $b = k$, and $c = 16$. So $k^2 - 4(1)(16) = 0 \\implies k^2 - 64 = 0 \\implies k^2 = 64$. Since $k > 0$, $k = 8$.",
        "hint": "For exactly one real solution, the discriminant $b^2 - 4ac$ must equal 0.",
        "sat_shortcut": "A perfect square trinomial is $(x + 4)^2 = x^2 + 8x + 16$, so $k = 2 \\times 4 = 8$.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "4", "is_correct": False},
            {"label": "B", "text": "8", "is_correct": True},
            {"label": "C", "text": "16", "is_correct": False},
            {"label": "D", "text": "32", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Quadratic functions",
        "subskill": "Vertex form of a parabola",
        "difficulty": Difficulty.EASY.value,
        "question_text": "The quadratic function $f$ is given by $f(x) = (x - 4)^2 + 7$. What is the minimum value of $f(x)$?",
        "explanation": "The function is in vertex form $f(x) = a(x - h)^2 + k$, where the vertex is $(h, k) = (4, 7)$. Since $a = 1 > 0$, the parabola opens upwards, and the minimum value of $f(x)$ is the $y$-coordinate of the vertex, which is 7.",
        "hint": "The square term $(x - 4)^2 \\ge 0$, so the minimum occurs when $(x - 4)^2 = 0$.",
        "sat_shortcut": "In vertex form $a(x-h)^2 + k$, the minimum/maximum is immediately $k = 7$.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$-4$", "is_correct": False},
            {"label": "B", "text": "4", "is_correct": False},
            {"label": "C", "text": "7", "is_correct": True},
            {"label": "D", "text": "11", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Quadratic functions",
        "subskill": "Projectile motion maximum height",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "The height $h$, in feet, of an object launched upwards from the ground after $t$ seconds is modeled by $h(t) = -16t^2 + 64t + 5$. What is the maximum height, in feet, reached by the object?",
        "explanation": "The maximum occurs at the vertex time $t = -\\frac{b}{2a} = -\\frac{64}{2(-16)} = \\frac{64}{32} = 2$ seconds. Substitute $t = 2$ into $h(t)$: $h(2) = -16(2)^2 + 64(2) + 5 = -16(4) + 128 + 5 = -64 + 128 + 5 = 69$ feet.",
        "hint": "Find the vertex $t = -b/(2a)$, then evaluate $h(t)$ at that time.",
        "sat_shortcut": "Graph `y = -16x^2 + 64x + 5` in Desmos and click the peak vertex point $(2, 69)$.",
        "estimated_time_seconds": 60,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "64", "is_correct": False},
            {"label": "B", "text": "69", "is_correct": True},
            {"label": "C", "text": "75", "is_correct": False},
            {"label": "D", "text": "85", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Polynomial expressions",
        "subskill": "Expanding binomials",
        "difficulty": Difficulty.EASY.value,
        "question_text": "Which expression is equivalent to $(2x + 3)(x - 4)$?",
        "explanation": "Expand using FOIL: First: $2x \\cdot x = 2x^2$. Outer: $2x \\cdot (-4) = -8x$. Inner: $3 \\cdot x = 3x$. Last: $3 \\cdot (-4) = -12$. Combine like terms: $2x^2 + (-8x + 3x) - 12 = 2x^2 - 5x - 12$.",
        "hint": "Multiply every term in the first parenthesis by every term in the second parenthesis.",
        "sat_shortcut": "Check middle term: $2(-4) + 3(1) = -8 + 3 = -5x$.",
        "estimated_time_seconds": 35,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$2x^2 - 12$", "is_correct": False},
            {"label": "B", "text": "$2x^2 - 5x - 12$", "is_correct": True},
            {"label": "C", "text": "$2x^2 + 5x - 12$", "is_correct": False},
            {"label": "D", "text": "$2x^2 - 11x - 12$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Polynomial expressions",
        "subskill": "Polynomial remainder theorem",
        "difficulty": Difficulty.HARD.value,
        "question_text": "If the polynomial $P(x) = x^3 - 2x^2 + kx - 6$ is divisible by $(x - 3)$, what is the value of the constant $k$?",
        "explanation": "By the Remainder Theorem, if $P(x)$ is divisible by $(x - 3)$, then $P(3) = 0$. Calculate $P(3)$: $3^3 - 2(3)^2 + k(3) - 6 = 27 - 18 + 3k - 6 = 3 + 3k$. Set $3 + 3k = 0 \\implies 3k = -3 \\implies k = -1$.",
        "hint": "Set $P(3) = 0$ since $(x - 3)$ is a factor.",
        "sat_shortcut": "Substitute $x = 3$ directly into the expression and solve for $k$: $27 - 18 - 6 + 3k = 0 \\implies 3 + 3k = 0 \\implies k = -1$.",
        "estimated_time_seconds": 65,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "$-2$", "is_correct": False},
            {"label": "B", "text": "$-1$", "is_correct": True},
            {"label": "C", "text": "1", "is_correct": False},
            {"label": "D", "text": "3", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Exponential functions",
        "subskill": "Evaluating exponential growth models",
        "difficulty": Difficulty.EASY.value,
        "question_text": "A population of bacteria doubles every hour. If the initial population is 500, which equation gives the population $P(t)$ after $t$ hours?",
        "explanation": "General exponential growth formula: $P(t) = P_0(1 + r)^t$ or $P_0(b)^t$. Here the initial population $P_0 = 500$ and doubling means base $b = 2$. Thus, $P(t) = 500(2)^t$.",
        "hint": "Doubling means the base of the exponential term is 2.",
        "sat_shortcut": "At $t = 0$, $P(0) = 500$. At $t = 1$, $P(1) = 1000$. Only $500(2)^t$ fits.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$P(t) = 500 + 2t$", "is_correct": False},
            {"label": "B", "text": "$P(t) = 500(2)^t$", "is_correct": True},
            {"label": "C", "text": "$P(t) = 2(500)^t$", "is_correct": False},
            {"label": "D", "text": "$P(t) = 500(1.2)^t$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Exponential functions",
        "subskill": "Exponential decay rate interpretation",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "The value $V(t)$, in dollars, of a piece of equipment $t$ years after purchase is given by $V(t) = 24{,}000(0.85)^t$. By what percentage does the value of the equipment decrease each year?",
        "explanation": "In the decay formula $V(t) = V_0(1 - r)^t$, the base is $1 - r = 0.85$. Solving for $r$: $r = 1 - 0.85 = 0.15 = 15\\%$. The value decreases by 15% each year.",
        "hint": "Subtract the decay factor 0.85 from 1 to find the rate of decrease.",
        "sat_shortcut": "$1.00 - 0.85 = 0.15 = 15\\%$.",
        "estimated_time_seconds": 40,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$8.5\\%$", "is_correct": False},
            {"label": "B", "text": "$15\\%$", "is_correct": True},
            {"label": "C", "text": "$24\\%$", "is_correct": False},
            {"label": "D", "text": "$85\\%$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Equivalent expressions",
        "subskill": "Laws of exponents",
        "difficulty": Difficulty.EASY.value,
        "question_text": "Which expression is equivalent to $(3x^2y)(4xy^3)$ for all real numbers $x$ and $y$?",
        "explanation": "Multiply the coefficients: $3 \\times 4 = 12$. Add exponents for like bases: for $x$, $x^2 \\cdot x^1 = x^{2+1} = x^3$; for $y$, $y^1 \\cdot y^3 = y^{1+3} = y^4$. Thus, the expression equals $12x^3y^4$.",
        "hint": "Multiply coefficients and add exponents of identical variables.",
        "sat_shortcut": "Coefficient is 12; powers are $2+1=3$ and $1+3=4$.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$7x^3y^4$", "is_correct": False},
            {"label": "B", "text": "$12x^2y^3$", "is_correct": False},
            {"label": "C", "text": "$12x^3y^4$", "is_correct": True},
            {"label": "D", "text": "$12x^2y^4$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Equivalent expressions",
        "subskill": "Simplifying rational expressions",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "For $x > 3$, which of the following is equivalent to $\\frac{x^2 - 9}{x^2 + 5x + 6}$?",
        "explanation": "Factor the numerator (difference of squares): $x^2 - 9 = (x - 3)(x + 3)$. Factor the denominator: $x^2 + 5x + 6 = (x + 2)(x + 3)$. Cancel the common factor $(x + 3)$: $\\frac{(x - 3)(x + 3)}{(x + 2)(x + 3)} = \\frac{x - 3}{x + 2}$.",
        "hint": "Factor both the numerator and denominator completely and cancel common factors.",
        "sat_shortcut": "Pick a test number like $x = 4$: $\\frac{16 - 9}{16 + 20 + 6} = \\frac{7}{42} = \\frac{1}{6}$. Test choices: $\\frac{4 - 3}{4 + 2} = \\frac{1}{6}$.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "$\\frac{x - 3}{x + 2}$", "is_correct": True},
            {"label": "B", "text": "$\\frac{x + 3}{x + 2}$", "is_correct": False},
            {"label": "C", "text": "$\\frac{x - 3}{x - 2}$", "is_correct": False},
            {"label": "D", "text": "$\\frac{-9}{5x + 6}$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Nonlinear equations",
        "subskill": "Radical equations and extraneous roots",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "What is the real solution to the equation $\\sqrt{2x + 5} = x - 5$?",
        "explanation": "Square both sides: $2x + 5 = (x - 5)^2 = x^2 - 10x + 25$. Rearrange to standard quadratic form: $x^2 - 12x + 20 = 0$. Factor: $(x - 10)(x - 2) = 0$, giving candidate solutions $x = 10$ and $x = 2$. Check for extraneous solutions: For $x = 2$: $\\sqrt{2(2) + 5} = \\sqrt{9} = 3$, but $2 - 5 = -3 \\neq 3$ (extraneous). For $x = 10$: $\\sqrt{2(10) + 5} = \\sqrt{25} = 5$ and $10 - 5 = 5$ (valid). Thus, $x = 10$ is the only real solution.",
        "hint": "Square both sides, but ALWAYS check your solutions in the original equation to filter out extraneous roots.",
        "sat_shortcut": "Notice $x - 5$ must be non-negative (since it equals a square root), so $x \\ge 5$. This instantly eliminates $x = 2$, leaving only $x = 10$.",
        "estimated_time_seconds": 65,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "2", "is_correct": False},
            {"label": "B", "text": "5", "is_correct": False},
            {"label": "C", "text": "10", "is_correct": True},
            {"label": "D", "text": "There are no real solutions", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Nonlinear equations",
        "subskill": "Rational algebraic equations",
        "difficulty": Difficulty.HARD.value,
        "question_text": "What is the solution set of $\\frac{4}{x - 2} = \\frac{3}{x + 1}$?",
        "explanation": "Cross-multiply: $4(x + 1) = 3(x - 2)$. Expand: $4x + 4 = 3x - 6$. Subtract $3x$ from both sides: $x + 4 = -6$. Subtract 4 from both sides: $x = -10$. Check restrictions: $x \\neq 2$ and $x \\neq -1$. Since $-10$ does not make any denominator zero, it is the valid solution.",
        "hint": "Cross-multiply and solve the resulting linear equation.",
        "sat_shortcut": "Cross-multiply mentally: $4x + 4 = 3x - 6 \\implies x = -10$.",
        "estimated_time_seconds": 50,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "$-10$", "is_correct": True},
            {"label": "B", "text": "$-6$", "is_correct": False},
            {"label": "C", "text": "2", "is_correct": False},
            {"label": "D", "text": "10", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.ADVANCED_MATH.value,
        "skill": "Nonlinear systems",
        "subskill": "Linear-quadratic system intersection",
        "difficulty": Difficulty.HARD.value,
        "question_text": "How many points of intersection do the graphs of $y = 2x - 3$ and $y = x^2 + 1$ have in the $xy$-plane?",
        "explanation": "Set the equations equal: $x^2 + 1 = 2x - 3 \\implies x^2 - 2x + 4 = 0$. Calculate the discriminant $\\Delta = b^2 - 4ac = (-2)^2 - 4(1)(4) = 4 - 16 = -12$. Since $\\Delta < 0$, there are no real solutions, meaning the line and parabola do not intersect.",
        "hint": "Equate the expressions for $y$ and examine the discriminant of the resulting quadratic.",
        "sat_shortcut": "Graph both equations in Desmos. The parabola is strictly above the line, so 0 intersection points.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "0", "is_correct": True},
            {"label": "B", "text": "1", "is_correct": False},
            {"label": "C", "text": "2", "is_correct": False},
            {"label": "D", "text": "Infinitely many", "is_correct": False},
        ],
    },

    # =========================================================================
    # DOMAIN 3: PROBLEM SOLVING & DATA ANALYSIS (16 new questions -> 21 total PS)
    # =========================================================================
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Ratios and proportions",
        "subskill": "Simple ratio scaling",
        "difficulty": Difficulty.EASY.value,
        "question_text": "In a box, the ratio of red marbles to blue marbles is $3:5$. If there are 45 blue marbles in the box, how many red marbles are there?",
        "explanation": "Set up a proportion: $\\frac{\\text{red}}{\\text{blue}} = \\frac{3}{5} = \\frac{r}{45}$. Cross-multiply or multiply both sides by 45: $r = 45 \\times \\frac{3}{5} = 9 \\times 3 = 27$.",
        "hint": "Divide 45 by 5 to find the value of one ratio part, then multiply by 3.",
        "sat_shortcut": "$45 / 5 = 9$, then $9 \\times 3 = 27$.",
        "estimated_time_seconds": 35,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "15", "is_correct": False},
            {"label": "B", "text": "27", "is_correct": True},
            {"label": "C", "text": "30", "is_correct": False},
            {"label": "D", "text": "75", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Ratios and proportions",
        "subskill": "Map scale proportion",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "On a road map, 1.5 inches represents an actual distance of 30 miles. If two towns are 4.5 inches apart on the map, what is the actual distance, in miles, between the two towns?",
        "explanation": "Since 1.5 inches corresponds to 30 miles, the scale is $\\frac{30}{1.5} = 20$ miles per inch. For 4.5 inches: $4.5 \\times 20 = 90$ miles. Alternatively, notice $4.5 = 3 \\times 1.5$, so the distance is $3 \\times 30 = 90$ miles.",
        "hint": "Notice that 4.5 inches is exactly 3 times 1.5 inches.",
        "sat_shortcut": "$4.5 / 1.5 = 3$. Multiply $3 \\times 30 = 90$.",
        "estimated_time_seconds": 40,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "60", "is_correct": False},
            {"label": "B", "text": "75", "is_correct": False},
            {"label": "C", "text": "90", "is_correct": True},
            {"label": "D", "text": "120", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Percentages",
        "subskill": "Single discount percentage",
        "difficulty": Difficulty.EASY.value,
        "question_text": "A jacket originally priced at \\$80 is on sale for 25% off. What is the sale price of the jacket?",
        "explanation": "A discount of 25% leaves $100\\% - 25\\% = 75\\%$ of the original price. Sale price $= 80 \\times 0.75 = 60$ dollars. Alternatively, the discount is $80 \\times 0.25 = 20$, and $80 - 20 = 60$.",
        "hint": "25% of 80 is one-fourth of 80.",
        "sat_shortcut": "$80 - 20 = 60$.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "\\$55", "is_correct": False},
            {"label": "B", "text": "\\$60", "is_correct": True},
            {"label": "C", "text": "\\$65", "is_correct": False},
            {"label": "D", "text": "\\$70", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Percentages",
        "subskill": "Successive percentage changes",
        "difficulty": Difficulty.HARD.value,
        "question_text": "The price of a computer stock increases by 20% in March and then decreases by 20% in April. Compared to the original price at the start of March, what is the net percentage change in the price of the stock?",
        "explanation": "Let the original price be 100. After a 20% increase: $100 \\times 1.20 = 120$. After a 20% decrease: $120 \\times 0.80 = 96$. The net change is $96 - 100 = -4$, which is a $4\\%$ decrease.",
        "hint": "Test with an initial value of 100.",
        "sat_shortcut": "Formula $(1 + 0.2)(1 - 0.2) = 1 - 0.04 = 0.96$, which means a 4% decrease.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "0% change (no change)", "is_correct": False},
            {"label": "B", "text": "4% decrease", "is_correct": True},
            {"label": "C", "text": "4% increase", "is_correct": False},
            {"label": "D", "text": "5% decrease", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Rates and units",
        "subskill": "Speed and travel time",
        "difficulty": Difficulty.EASY.value,
        "question_text": "A train travels at a constant speed of 75 miles per hour. How many miles does the train travel in 2.4 hours?",
        "explanation": "Distance $=$ rate $\\times$ time: $D = 75 \\times 2.4$. Calculate: $75 \\times 2 = 150$, and $75 \\times 0.4 = 30$. Total distance $= 150 + 30 = 180$ miles.",
        "hint": "Use Distance = Rate $\\times$ Time.",
        "sat_shortcut": "$75 \\times 2.4 = 180$.",
        "estimated_time_seconds": 35,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "150", "is_correct": False},
            {"label": "B", "text": "165", "is_correct": False},
            {"label": "C", "text": "180", "is_correct": True},
            {"label": "D", "text": "195", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Rates and units",
        "subskill": "Unit conversion",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "A vehicle is traveling at 60 miles per hour. Given that 1 mile = 5,280 feet, what is the vehicle's speed in feet per second?",
        "explanation": "Convert miles to feet and hours to seconds: $\\frac{60 \\text{ miles}}{1 \\text{ hour}} \\times \\frac{5{,}280 \\text{ feet}}{1 \\text{ mile}} \\times \\frac{1 \\text{ hour}}{3{,}600 \\text{ seconds}} = \\frac{60 \\times 5{,}280}{3{,}600} = \\frac{5{,}280}{60} = 88$ feet per second.",
        "hint": "There are 3,600 seconds in 1 hour.",
        "sat_shortcut": "$60 \\times 5280 / 3600 = 88$.",
        "estimated_time_seconds": 60,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "66", "is_correct": False},
            {"label": "B", "text": "88", "is_correct": True},
            {"label": "C", "text": "96", "is_correct": False},
            {"label": "D", "text": "120", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Rates and units",
        "subskill": "Combined work rate",
        "difficulty": Difficulty.HARD.value,
        "question_text": "Pump A can empty a water reservoir in 6 hours alone. Pump B can empty the same reservoir in 3 hours alone. If both pumps work together at their constant rates, how many hours will it take to empty the reservoir?",
        "explanation": "Rate of Pump A is $\\frac{1}{6}$ reservoir/hour. Rate of Pump B is $\\frac{1}{3}$ reservoir/hour. Combined rate $= \\frac{1}{6} + \\frac{1}{3} = \\frac{1}{6} + \\frac{2}{6} = \\frac{3}{6} = \\frac{1}{2}$ reservoir/hour. Time required $= \\frac{1}{\\text{rate}} = \\frac{1}{1/2} = 2$ hours.",
        "hint": "Add the hourly rates together: $\\frac{1}{6} + \\frac{1}{3}$.",
        "sat_shortcut": "Product over sum formula: $\\frac{a \\times b}{a + b} = \\frac{6 \\times 3}{6 + 3} = \\frac{18}{9} = 2$ hours.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "1.5", "is_correct": False},
            {"label": "B", "text": "2.0", "is_correct": True},
            {"label": "C", "text": "2.5", "is_correct": False},
            {"label": "D", "text": "4.5", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Tables and graphs",
        "subskill": "Frequency table analysis",
        "difficulty": Difficulty.EASY.value,
        "question_text": "A survey asked 40 students how many books they read during summer break:\n- 0 books: 8 students\n- 1 book: 14 students\n- 2 books: 12 students\n- 3 or more books: 6 students\n\nWhat percentage of the surveyed students read at least 2 books?",
        "explanation": "\"At least 2 books\" means 2 books or 3+ books: $12 + 6 = 18$ students. The percentage is $\\frac{18}{40} \\times 100\\% = \\frac{9}{20} \\times 100\\% = 45\\%$.",
        "hint": "Sum the counts for \"2 books\" and \"3 or more books\", then divide by 40.",
        "sat_shortcut": "$18 / 40 = 0.45 = 45\\%$.",
        "estimated_time_seconds": 40,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "30%", "is_correct": False},
            {"label": "B", "text": "45%", "is_correct": True},
            {"label": "C", "text": "55%", "is_correct": False},
            {"label": "D", "text": "70%", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Tables and graphs",
        "subskill": "Relative frequency from two-way table",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "The table below summarizes membership in two clubs:\n\n| | Chess Club | Robotics Club | Total |\n|---|---|---|---|\n| Grade 10 | 12 | 18 | 30 |\n| Grade 11 | 20 | 10 | 30 |\n| Total | 32 | 28 | 60 |\n\nIf a Grade 10 student is selected at random, what is the probability that the student is in the Robotics Club?",
        "explanation": "We are given that the selected student is in Grade 10 (conditional condition). The total number of Grade 10 students is 30. Of these, 18 are in the Robotics Club. Probability $= \\frac{18}{30} = \\frac{3}{5} = 0.60$.",
        "hint": "Look only at the Grade 10 row, where the row total is 30.",
        "sat_shortcut": "Condition restricts denominator to Grade 10 total: $18 / 30 = 0.60$.",
        "estimated_time_seconds": 45,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$\\frac{18}{60}$", "is_correct": False},
            {"label": "B", "text": "$\\frac{18}{28}$", "is_correct": False},
            {"label": "C", "text": "$\\frac{18}{30}$", "is_correct": True},
            {"label": "D", "text": "$\\frac{30}{60}$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Scatterplots",
        "subskill": "Line of best fit prediction",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "A scatterplot shows the relationship between hours of study $x$ and exam score $y$. The line of best fit is given by $\\hat{y} = 5.2x + 48$. Based on this model, what is the predicted exam score for a student who studied for 7 hours?",
        "explanation": "Substitute $x = 7$ into the prediction equation: $\\hat{y} = 5.2(7) + 48 = 36.4 + 48 = 84.4$.",
        "hint": "Substitute $x = 7$ into the line of best fit equation.",
        "sat_shortcut": "$5.2 \\times 7 = 36.4$, plus $48 = 84.4$.",
        "estimated_time_seconds": 40,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "78.4", "is_correct": False},
            {"label": "B", "text": "84.4", "is_correct": True},
            {"label": "C", "text": "88.2", "is_correct": False},
            {"label": "D", "text": "92.0", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Scatterplots",
        "subskill": "Interpreting slope of line of best fit",
        "difficulty": Difficulty.HARD.value,
        "question_text": "In a scatterplot relating ambient temperature $T$ in degrees Celsius to daily electricity consumption $E$ in kilowatt-hours, the line of best fit has equation $E = 2.8T + 14.5$. What does the slope $2.8$ represent in this context?",
        "explanation": "The slope $\\frac{\\Delta E}{\\Delta T} = 2.8$ indicates that for each $1^\\circ\\text{C}$ increase in ambient temperature, the predicted daily electricity consumption increases by 2.8 kilowatt-hours.",
        "hint": "Slope is change in the dependent variable ($E$) per 1 unit increase in the independent variable ($T$).",
        "sat_shortcut": "Slope $=$ increase in $y$ for each unit increase in $x$.",
        "estimated_time_seconds": 45,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "The electricity consumption when the temperature is $0^\\circ\\text{C}$", "is_correct": False},
            {"label": "B", "text": "The predicted increase in kilowatt-hours of electricity used for each $1^\\circ\\text{C}$ increase in temperature", "is_correct": True},
            {"label": "C", "text": "The average daily ambient temperature throughout the year", "is_correct": False},
            {"label": "D", "text": "The maximum temperature at which electricity is consumed", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Statistics",
        "subskill": "Mean and median calculation",
        "difficulty": Difficulty.EASY.value,
        "question_text": "What is the median of the data set: $\\{5, 8, 12, 15, 20\\}$?",
        "explanation": "The data set has 5 elements and is already sorted in ascending order. The middle element (3rd element) is 12.",
        "hint": "The median of an odd number of sorted elements is the middle value.",
        "sat_shortcut": "Count 2 values on each side: middle is 12.",
        "estimated_time_seconds": 25,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "8", "is_correct": False},
            {"label": "B", "text": "12", "is_correct": True},
            {"label": "C", "text": "14", "is_correct": False},
            {"label": "D", "text": "15", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Statistics",
        "subskill": "Impact of outliers on mean vs median",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "A dataset of 20 home prices has a mean of \\$350,000 and a median of \\$340,000. An additional luxury home priced at \\$3,500,000 is added to the dataset. How will adding this new home affect the mean and median?",
        "explanation": "An extreme high outlier heavily pulls the mean upward because the mean incorporates all numerical values directly. The median, being resistant to outliers, shifts by at most one position and changes only marginally. Thus, the mean increases substantially more than the median.",
        "hint": "The mean is sensitive to extreme outliers; the median is robust.",
        "sat_shortcut": "Mean is heavily pulled toward outliers; median resists outliers.",
        "estimated_time_seconds": 50,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "Both the mean and median will increase by the exact same dollar amount", "is_correct": False},
            {"label": "B", "text": "The mean will increase substantially more than the median", "is_correct": True},
            {"label": "C", "text": "The median will increase substantially more than the mean", "is_correct": False},
            {"label": "D", "text": "Neither the mean nor the median will change", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Probability",
        "subskill": "Simple discrete probability",
        "difficulty": Difficulty.EASY.value,
        "question_text": "An integer is chosen at random from 1 to 25, inclusive. What is the probability that the chosen number is a multiple of 6?",
        "explanation": "Multiples of 6 between 1 and 25 are: 6, 12, 18, 24. There are 4 favorable outcomes out of 25 possible outcomes. Probability $= \\frac{4}{25}$.",
        "hint": "List the multiples of 6 up to 25: 6, 12, 18, 24.",
        "sat_shortcut": "$25 // 6 = 4$. Probability is $4/25$.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$\\frac{3}{25}$", "is_correct": False},
            {"label": "B", "text": "$\\frac{4}{25}$", "is_correct": True},
            {"label": "C", "text": "$\\frac{5}{25}$", "is_correct": False},
            {"label": "D", "text": "$\\frac{6}{25}$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Data interpretation",
        "subskill": "Margin of error in survey estimates",
        "difficulty": Difficulty.HARD.value,
        "question_text": "A random sample of 800 registered voters in a city found that 54% support a proposed library renovation, with an associated margin of error of 3.5% at a 95% confidence level. Which statement is the most appropriate conclusion?",
        "explanation": "The confidence interval is $54\\% \\pm 3.5\\%$, which ranges from $50.5\\%$ to $57.5\\%$. Because the entire interval is above $50\\%$, it is plausible that a majority (more than 50%) of all registered voters in the city support the renovation.",
        "hint": "Compute the interval: $54 - 3.5 = 50.5\\%$ and $54 + 3.5 = 57.5\\%$.",
        "sat_shortcut": "Both bounds of $50.5\\%$ to $57.5\\%$ are strictly greater than $50\\%$.",
        "estimated_time_seconds": 60,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "Exactly 54% of all voters in the city support the renovation", "is_correct": False},
            {"label": "B", "text": "It is plausible that the true percentage of registered voters in the city who support the renovation is between 50.5% and 57.5%", "is_correct": True},
            {"label": "C", "text": "Every voter in the sample had a 3.5% probability of changing their vote", "is_correct": False},
            {"label": "D", "text": "A majority of voters in the entire state support the renovation", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.PROBLEM_SOLVING_DATA_ANALYSIS.value,
        "skill": "Data interpretation",
        "subskill": "Sample generalizability and selection bias",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "A high school principal wants to determine student satisfaction with the cafeteria food. The principal surveys the first 50 students who enter the cafeteria on Monday. To which group can the results of this survey be reliably generalized?",
        "explanation": "Because the sample was taken only from students entering the cafeteria on Monday morning (convenience sample), it is subject to selection bias (students who dislike the food might not go to the cafeteria at all). Therefore, the findings can only be generalized to students who arrive early at the cafeteria on Mondays, not the entire student body.",
        "hint": "Convenience sampling limits the population to which conclusions can be generalized.",
        "sat_shortcut": "SAT rule: conclusions can only be generalized to populations from which a truly random sample was selected.",
        "estimated_time_seconds": 50,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "All high school students in the school district", "is_correct": False},
            {"label": "B", "text": "All students enrolled in this high school", "is_correct": False},
            {"label": "C", "text": "Only students who enter the cafeteria early on Monday", "is_correct": True},
            {"label": "D", "text": "All teachers and students at the high school", "is_correct": False},
        ],
    },

    # =========================================================================
    # DOMAIN 4: GEOMETRY & TRIGONOMETRY (16 new questions -> 21 total Geom/Trig)
    # =========================================================================
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Lines and angles",
        "subskill": "Parallel lines and alternate interior angles",
        "difficulty": Difficulty.EASY.value,
        "question_text": "Two parallel lines $L_1$ and $L_2$ are intersected by a transversal line. One of the interior angles is $65^\\circ$. What is the degree measure of its consecutive interior angle?",
        "explanation": "Consecutive interior angles between parallel lines are supplementary (sum to $180^\\circ$). Therefore, the consecutive interior angle is $180^\\circ - 65^\\circ = 115^\\circ$.",
        "hint": "Consecutive (same-side) interior angles add up to $180^\\circ$.",
        "sat_shortcut": "$180 - 65 = 115$.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$25^\\circ$", "is_correct": False},
            {"label": "B", "text": "$65^\\circ$", "is_correct": False},
            {"label": "C", "text": "$115^\\circ$", "is_correct": True},
            {"label": "D", "text": "$125^\\circ$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Lines and angles",
        "subskill": "Vertical and supplementary angles",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "In the $xy$-plane, two intersecting lines form vertical angles with measures $(3x + 15)^\\circ$ and $(5x - 25)^\\circ$. What is the degree measure of one of the angles supplementary to these?",
        "explanation": "Vertical angles are equal: $3x + 15 = 5x - 25$. Subtract $3x$: $15 = 2x - 25$. Add 25: $2x = 40 \\implies x = 20$. The vertical angle measure is $3(20) + 15 = 75^\\circ$. Supplementary angles add to $180^\\circ$, so the supplementary angle is $180^\\circ - 75^\\circ = 105^\\circ$.",
        "hint": "Vertical angles are equal. Find $x$, calculate the angle, then subtract from $180^\\circ$.",
        "sat_shortcut": "$5x - 3x = 15 + 25 \\implies 2x = 40 \\implies x = 20$. Angle is $75^\\circ$, supplementary is $105^\\circ$.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$75^\\circ$", "is_correct": False},
            {"label": "B", "text": "$85^\\circ$", "is_correct": False},
            {"label": "C", "text": "$105^\\circ$", "is_correct": True},
            {"label": "D", "text": "$115^\\circ$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Triangles",
        "subskill": "Triangle angle sum theorem",
        "difficulty": Difficulty.EASY.value,
        "question_text": "In triangle $ABC$, the measure of angle $A$ is $42^\\circ$ and the measure of angle $B$ is $68^\\circ$. What is the degree measure of angle $C$?",
        "explanation": "The sum of interior angles in any triangle is $180^\\circ$. Therefore, angle $C = 180^\\circ - (42^\\circ + 68^\\circ) = 180^\\circ - 110^\\circ = 70^\\circ$.",
        "hint": "Subtract the sum of the known two angles from $180^\\circ$.",
        "sat_shortcut": "$180 - (42 + 68) = 180 - 110 = 70^\\circ$.",
        "estimated_time_seconds": 25,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$60^\\circ$", "is_correct": False},
            {"label": "B", "text": "$70^\\circ$", "is_correct": True},
            {"label": "C", "text": "$80^\\circ$", "is_correct": False},
            {"label": "D", "text": "$90^\\circ$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Triangles",
        "subskill": "Isosceles triangle properties",
        "difficulty": Difficulty.HARD.value,
        "question_text": "In isosceles triangle $PQR$, $PQ = PR$ and the measure of angle $P$ is $40^\\circ$. If an altitude is drawn from vertex $P$ to side $QR$, what is the measure of each angle formed between the altitude and the congruent legs?",
        "explanation": "In an isosceles triangle with $PQ = PR$, the altitude drawn from the vertex angle $P$ bisects the vertex angle. Since angle $P = 40^\\circ$, each angle formed between the altitude and leg $PQ$ (or $PR$) is $\\frac{40^\\circ}{2} = 20^\\circ$.",
        "hint": "The altitude to the base of an isosceles triangle bisects the vertex angle.",
        "sat_shortcut": "$40 / 2 = 20^\\circ$.",
        "estimated_time_seconds": 45,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$20^\\circ$", "is_correct": True},
            {"label": "B", "text": "$35^\\circ$", "is_correct": False},
            {"label": "C", "text": "$40^\\circ$", "is_correct": False},
            {"label": "D", "text": "$70^\\circ$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Similarity",
        "subskill": "Similar triangle side ratios",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "Triangle $ABC$ is similar to triangle $DEF$, with vertices $A, B, C$ corresponding to $D, E, F$, respectively. If $AB = 6$, $DE = 9$, and $BC = 8$, what is the length of side $EF$?",
        "explanation": "Corresponding sides of similar triangles are proportional: $\\frac{DE}{AB} = \\frac{EF}{BC}$. The scale factor is $\\frac{9}{6} = 1.5$. Therefore, $EF = 8 \\times 1.5 = 12$.",
        "hint": "Set up a proportion: $\\frac{6}{9} = \\frac{8}{EF}$.",
        "sat_shortcut": "Scale factor is $9/6 = 3/2$. Side $EF = 8 \\times (3/2) = 12$.",
        "estimated_time_seconds": 40,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "10", "is_correct": False},
            {"label": "B", "text": "11", "is_correct": False},
            {"label": "C", "text": "12", "is_correct": True},
            {"label": "D", "text": "14", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Similarity",
        "subskill": "Ratio of areas of similar figures",
        "difficulty": Difficulty.HARD.value,
        "question_text": "Two similar polygons have corresponding sides in the ratio $3:5$. If the area of the smaller polygon is 54 square centimeters, what is the area, in square centimeters, of the larger polygon?",
        "explanation": "If the ratio of corresponding side lengths of two similar figures is $\\frac{a}{b}$, the ratio of their areas is $\\left(\\frac{a}{b}\\right)^2$. Here, the area ratio is $\\left(\\frac{3}{5}\\right)^2 = \\frac{9}{25}$. Setting up the proportion: $\\frac{54}{A} = \\frac{9}{25} \\implies A = 54 \\times \\frac{25}{9} = 6 \\times 25 = 150$.",
        "hint": "The ratio of areas is the SQUARE of the ratio of side lengths.",
        "sat_shortcut": "Area ratio is $(5/3)^2 = 25/9$. Multiply $54 \\times 25 / 9 = 6 \\times 25 = 150$.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "90", "is_correct": False},
            {"label": "B", "text": "120", "is_correct": False},
            {"label": "C", "text": "150", "is_correct": True},
            {"label": "D", "text": "225", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Area and volume",
        "subskill": "Rectangle area from perimeter",
        "difficulty": Difficulty.EASY.value,
        "question_text": "A rectangular garden has a perimeter of 36 meters and a length of 10 meters. What is the area of the garden, in square meters?",
        "explanation": "Perimeter formula: $P = 2l + 2w$. We have $36 = 2(10) + 2w \\implies 36 = 20 + 2w \\implies 2w = 16 \\implies w = 8$. The area is $A = l \\times w = 10 \\times 8 = 80$ square meters.",
        "hint": "Find the width first using Perimeter = $2(l + w)$.",
        "sat_shortcut": "Half perimeter is $18$. Width is $18 - 10 = 8$. Area $= 10 \\times 8 = 80$.",
        "estimated_time_seconds": 35,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "60", "is_correct": False},
            {"label": "B", "text": "72", "is_correct": False},
            {"label": "C", "text": "80", "is_correct": True},
            {"label": "D", "text": "90", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Area and volume",
        "subskill": "Right circular cylinder volume",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "A right circular cylinder has a radius of 4 inches and a height of 9 inches. What is the volume of the cylinder, in cubic inches?",
        "explanation": "The volume of a right circular cylinder is $V = \\pi r^2 h$. Substitute $r = 4$ and $h = 9$: $V = \\pi (4)^2 (9) = \\pi (16)(9) = 144\\pi$ cubic inches.",
        "hint": "Use $V = \\pi r^2 h$.",
        "sat_shortcut": "$16 \\times 9 = 144$, so $144\\pi$.",
        "estimated_time_seconds": 40,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$72\\pi$", "is_correct": False},
            {"label": "B", "text": "$108\\pi$", "is_correct": False},
            {"label": "C", "text": "$144\\pi$", "is_correct": True},
            {"label": "D", "text": "$288\\pi$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Area and volume",
        "subskill": "Scaling volume of three-dimensional solids",
        "difficulty": Difficulty.HARD.value,
        "question_text": "If all linear dimensions of a rectangular prism are multiplied by 3, by what factor does the volume of the prism increase?",
        "explanation": "Volume of a rectangular prism is $V = l \\times w \\times h$. When every linear dimension is multiplied by 3, the new volume becomes $V_{\\text{new}} = (3l)(3w)(3h) = 27(l \\times w \\times h) = 27V$. Thus, the volume increases by a factor of $3^3 = 27$.",
        "hint": "When linear dimensions scale by $k$, volume scales by $k^3$.",
        "sat_shortcut": "$3^3 = 27$.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "3", "is_correct": False},
            {"label": "B", "text": "9", "is_correct": False},
            {"label": "C", "text": "18", "is_correct": False},
            {"label": "D", "text": "27", "is_correct": True},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Circles",
        "subskill": "Circumference from circle area",
        "difficulty": Difficulty.EASY.value,
        "question_text": "The area of a circle is $49\\pi$. What is the circumference of this circle?",
        "explanation": "Area formula: $A = \\pi r^2 = 49\\pi \\implies r^2 = 49 \\implies r = 7$. Circumference formula: $C = 2\\pi r = 2\\pi(7) = 14\\pi$.",
        "hint": "Find the radius $r = \\sqrt{49} = 7$, then compute $2\\pi r$.",
        "sat_shortcut": "$r = 7$, so $C = 2 \\times 7\\pi = 14\\pi$.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$7\\pi$", "is_correct": False},
            {"label": "B", "text": "$14\\pi$", "is_correct": True},
            {"label": "C", "text": "$21\\pi$", "is_correct": False},
            {"label": "D", "text": "$28\\pi$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Circles",
        "subskill": "Arc length calculation",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "A circle with radius 6 has a central angle measuring $60^\\circ$. What is the length of the intercepted arc?",
        "explanation": "Arc length formula: $s = 2\\pi r \\times \\frac{\\theta}{360^\\circ}$. With $r = 6$ and $\\theta = 60^\\circ$: $s = 2\\pi(6) \\times \\frac{60}{360} = 12\\pi \\times \\frac{1}{6} = 2\\pi$.",
        "hint": "Arc length is the fraction of total circumference: $\\frac{60}{360} = \\frac{1}{6}$.",
        "sat_shortcut": "Circumference is $12\\pi$. $1/6$ of $12\\pi$ is $2\\pi$.",
        "estimated_time_seconds": 40,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$\\pi$", "is_correct": False},
            {"label": "B", "text": "$2\\pi$", "is_correct": True},
            {"label": "C", "text": "$3\\pi$", "is_correct": False},
            {"label": "D", "text": "$6\\pi$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Circles",
        "subskill": "Circle equation in coordinate plane",
        "difficulty": Difficulty.HARD.value,
        "question_text": "A circle in the $xy$-plane has equation $(x - 3)^2 + (y + 4)^2 = 25$. If the line $y = 1$ intersects the circle at $(a, 1)$, what is the value of $a$?",
        "explanation": "Substitute $y = 1$ into the circle equation: $(x - 3)^2 + (1 + 4)^2 = 25 \\implies (x - 3)^2 + 25 = 25 \\implies (x - 3)^2 = 0 \\implies x - 3 = 0 \\implies x = 3$. Thus, the line $y = 1$ is tangent to the circle at $(3, 1)$, and $a = 3$.",
        "hint": "Substitute $y = 1$ into the circle equation.",
        "sat_shortcut": "The highest point on the circle is center $(3, -4)$ plus radius $5$, which is $(3, 1)$. The line $y = 1$ touches at exactly $x = 3$.",
        "estimated_time_seconds": 55,
        "desmos_allowed": True,
        "desmos_recommended": True,
        "options": [
            {"label": "A", "text": "$-3$", "is_correct": False},
            {"label": "B", "text": "0", "is_correct": False},
            {"label": "C", "text": "3", "is_correct": True},
            {"label": "D", "text": "5", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Right triangles",
        "subskill": "Pythagorean theorem application",
        "difficulty": Difficulty.EASY.value,
        "question_text": "In a right triangle, the lengths of the two legs are 5 and 12. What is the length of the hypotenuse?",
        "explanation": "Use the Pythagorean theorem: $a^2 + b^2 = c^2 \\implies 5^2 + 12^2 = c^2 \\implies 25 + 144 = c^2 \\implies c^2 = 169 \\implies c = 13$. (This is the standard 5-12-13 Pythagorean triple).",
        "hint": "Recall the classic 5-12-13 Pythagorean triple.",
        "sat_shortcut": "Pythagorean triple: 5-12-13.",
        "estimated_time_seconds": 25,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "13", "is_correct": True},
            {"label": "B", "text": "14", "is_correct": False},
            {"label": "C", "text": "15", "is_correct": False},
            {"label": "D", "text": "17", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Right triangles",
        "subskill": "Special right triangles 30-60-90",
        "difficulty": Difficulty.MEDIUM.value,
        "question_text": "In a 30°-60°-90° right triangle, the side opposite the 30° angle has length 6. What is the length of the hypotenuse?",
        "explanation": "In a 30°-60°-90° triangle, the side lengths are in ratio $1 : \\sqrt{3} : 2$. The hypotenuse is twice the length of the shortest side (opposite the 30° angle): $2 \\times 6 = 12$.",
        "hint": "The hypotenuse is always 2 times the side opposite the 30° angle.",
        "sat_shortcut": "$2 \\times 6 = 12$.",
        "estimated_time_seconds": 30,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$6\\sqrt{3}$", "is_correct": False},
            {"label": "B", "text": "10", "is_correct": False},
            {"label": "C", "text": "12", "is_correct": True},
            {"label": "D", "text": "18", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Trigonometry",
        "subskill": "Complementary angle trigonometric identity",
        "difficulty": Difficulty.EASY.value,
        "question_text": "If $\\sin(x^\\circ) = \\frac{3}{5}$, what is the value of $\\cos((90 - x)^\\circ)$?",
        "explanation": "By the cofunction identity for complementary angles, $\\cos(90^\\circ - x) = \\sin(x)$. Therefore, $\\cos((90 - x)^\\circ) = \\frac{3}{5}$.",
        "hint": "Cofunction identity: $\\sin(x) = \\cos(90^\\circ - x)$.",
        "sat_shortcut": "The sine of an angle always equals the cosine of its complement: exactly $\\frac{3}{5}$.",
        "estimated_time_seconds": 25,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$\\frac{3}{5}$", "is_correct": True},
            {"label": "B", "text": "$\\frac{4}{5}$", "is_correct": False},
            {"label": "C", "text": "$\\frac{3}{4}$", "is_correct": False},
            {"label": "D", "text": "$\\frac{5}{3}$", "is_correct": False},
        ],
    },
    {
        "subject": Subject.MATH.value,
        "domain": MathDomain.GEOMETRY_TRIGONOMETRY.value,
        "skill": "Trigonometry",
        "subskill": "Radian degree conversion and unit circle",
        "difficulty": Difficulty.HARD.value,
        "question_text": "What is the degree measure equivalent to $\\frac{5\\pi}{6}$ radians?",
        "explanation": "To convert radians to degrees, multiply by $\\frac{180^\\circ}{\\pi}$: $\\frac{5\\pi}{6} \\times \\frac{180^\\circ}{\\pi} = 5 \\times \\frac{180^\\circ}{6} = 5 \\times 30^\\circ = 150^\\circ$.",
        "hint": "Replace $\\pi$ radians with $180^\\circ$.",
        "sat_shortcut": "$5 \\times (180 / 6) = 5 \\times 30 = 150^\\circ$.",
        "estimated_time_seconds": 35,
        "desmos_allowed": True,
        "desmos_recommended": False,
        "options": [
            {"label": "A", "text": "$120^\\circ$", "is_correct": False},
            {"label": "B", "text": "$135^\\circ$", "is_correct": False},
            {"label": "C", "text": "$150^\\circ$", "is_correct": True},
            {"label": "D", "text": "$210^\\circ$", "is_correct": False},
        ],
    },
]
